name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: '${{ env.NODE_VERSION }}'
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
        - name: check node version
          run: node -v
