name: ex6 npm test
on: 
  workflow_dispatch:
env:
  cache-name: node
  
jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: cache node modules
          uses: actions/cache@v3
          with:
            path: ./node_modules
            key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        - name: run install
          shell: bash
          run: |
            npm install

  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: cache node modules
          uses: actions/cache@v3
          with:
            path: ./node_modules
            key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        - name: run test
          shell: bash
          run: |
            npm test
