name: ex6 build docker
on: 
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: run install
        shell: bash
        run: |
          npm install
          npm test
  build-docker:
    runs-on: ubuntu-latest
    needs: run-npm-install
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t ${{ github.sha }} .
